fibonacci_sequence = [0,1]
print(fibonacci_sequence)
fibonacci_sequence.append (fibonacci_sequence[0]+fibonacci_sequence[1])
print (fibonacci_sequence)
fibonacci_sequence.append (fibonacci_sequence[1]+fibonacci_sequence[2])
print(fibonacci_sequence)
fibonacci_sequence.append (fibonacci_sequence[2]+fibonacci_sequence[3])
print(fibonacci_sequence)
fibonacci_sequence.append (fibonacci_sequence[3]+fibonacci_sequence[4])
print(fibonacci_sequence)
fibonacci_sequence.append (fibonacci_sequence[4]+fibonacci_sequence[5])
print(fibonacci_sequence)
fibonacci_sequence.append (fibonacci_sequence[5]+fibonacci_sequence[6])
print(fibonacci_sequence)
fibonacci_sequence.append (fibonacci_sequence[6]+fibonacci_sequence[7])
print(fibonacci_sequence)
fibonacci_sequence.append (fibonacci_sequence[7]+fibonacci_sequence[8])
print(fibonacci_sequence)
